# This is a TOML document. Boom.

[user]
    username = "Ren"
    passwd = "love you baby"

[mysql]
addr = "127.0.0.1:3306"
dsn = "root:1101@tcp(127.0.0.1:3306)/demo?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 2